### PR TITLE
replace geo files from chocolate4u project

### PR DESCRIPTION
**Pull request by mmrabbani**
@chocolate4u optimized geo files with Iranian needs. with this change, user can define Iran related rules easily.

More Information:
https://github.com/Chocolate4U/Iran-v2ray-rules

### CODE REVIEW

**Comment by irgfw** [comment]
https://github.com/GFW-knocker/MahsaNG/pull/70#issuecomment-2308512310

**Comment by mmrabbani** [comment]
Answer1: there are around extra 50.000 Iranian address in chacolate4u. I don't know how how many extra IP it has. It has IP2location list,
Answer2: Geo lists cannot redirect any address and so, there is no phishing scenario. If a non-iranian website is included in the list by mistake, only traffic of that website is spitted from VPN tunnel. These most popular server panels also use chacolate4u list. There is no risk.
https://github.com/MHSanaei/3x-ui/
https://github.com/alireza0/x-ui/

Answer3: V2rayNG (and therefore NikaNG) has a predefine rule "bypass LAN and mainland address the proxy" that is default but user can disable it. We can change it to "bypass LAN, China, and Iran address the proxy". It would be better to change the geo files without changing the rules and postpone changing rules to the next version.

**Comment by GFW-knocker** [comment]
@mmrabbani 
thank you
i will set iran and china to direct in next release.

**Comment by irgfw** [comment]
@GFW-knocker 
Besides many more Iranian IP and Domain addresses in chocolate4u, the `category-ads-all` contains All foreign and Persian ads (from [MasterKia/PersianBlocker](https://github.com/MasterKia/PersianBlocker)), which, to this day, is the complete Persian ad rule list. 
Also, the choco4u has phishing, cryptominers, and malware lists for blocking.

**Pull request merged**
